services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"


volumes:
  mariadb_data:
    name: mariadb_database
    driver: local
    driver_opts:
       type: none
       o: bind
       device: /home/yyean-wa/data/mariadb

  wordpress_data:
    name: wordpress_database
    driver: local
    driver_opts:
       type: none
       o: bind
       device: /home/yyean-wa/data/wordpress

networks:
  inception:
    name: inception

