services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    working_dir: /requirments/nginx
    volumes:
      - wordpress_files:/var/www/html/wordpress
    networks:
      - inception
    restart: always
    ports:
      - 127.0.0.1:443:443
    expose:
      - 9000

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    working_dir: /requirements/mariadb
    volumes:
      - wordpress_database:/var/lib/mysql
    networks:
      - inception
    restart: always
    expose:
      - 3306

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    working_dir: /requirements/wordpress
    volumes:
      - wordpress_files:/var/www/html/wordpress
    networks:
      - inception
    restart: always
    expose:
     - 3306
     - 9000

volumes:
  wordpress_database:
    name: wordpress_database
    driver: local
    driver_opts:
       type: none
       o: bind
       device: /home/yyean-wa/data/wordpress_database

  wordpress_files:
    name: wordpress_files
    driver: local
    driver_opts:
       type: none
       o: bind
       device: /home/yyean-wa/data/wordpress_files

networks:
  inception:

