services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    volumes:
      - nginx_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    ports:
      - "443:443"

volumes:
  mariadb_data:
  nginx_data:

networks:
  inception:
    name: inception

